[build]

publish = "public"
command = "zola build"

[build.environment]
# Set the version name that you want to use and Netlify will automatically use it.
ZOLA_VERSION = "0.12.2"



[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin",
    Cross-Origin-Embedder-Policy = "require-corp"

[context.deploy-preview]
command = "zola build --base-url $DEPLOY_PRIME_URL"


