# On every push this script is executed
on: push
name: Build and deploy GH Pages
jobs:
  build:
    name: shalzz/zola-deploy-action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build & deploy
      uses: shalzz/zola-deploy-action@c34a7626cd84c9c90499afeb310070ea838a8d1a
      env:
        PAGES_BRANCH: gh-pages
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}