# On every push this script is executed
on: push
name: Build and deploy GH Pages
jobs:
  build:
    name: shalzz/zola-deploy-action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build & deploy
      uses: shalzz/zola-deploy-action@v0.18.0
      env:
        PAGES_BRANCH: gh-pages
        GITHUB_TOKEN: ${{ secrets.TOKEN }}